### ISSUE TITLE
Bug: extra suggestion after quotes

### ISSUE THREAD

**Issue by itepastra** [ThePrimeagen/htmx-lsp#17]
When I use the LSP to complete a value, and then close the quotes, it starts suggesting the same attributes again.

current behaviour:
![image](https://github.com/ThePrimeagen/htmx-lsp/assets/27058689/d28e31d1-bd2b-490b-a8dd-6d3bddee67f9)

expected behaviour:
It doesn't suggest the attributes after the quotes.

**Comment by itepastra** [comment]
This is already fixed in pr #16

**Comment by cristianoliveira** [comment]
The #16 indeed fixes that error but unfortunately, it doesn't cover another bug I discovered yesterday, which happens when there is an open quote but the closed quote is only in the new line for instance:
```html
<body>
	<h1 class="uppercase text-blue-400 font-bold" hx-target="(cursor here) > Ergo UI</h1>
	<div>
		<div class="bg-gray-500 text-white font-bold" hx-get="/status" hx-target="#ergo-status"
			hx-swap="innerHTML" hx-trigger="load, every 5s">Status</div>
	</div>
</body>
```

I fixed the bug above too in another change, but I'm not sure it makes sense to merge everything in a unique PR. @ThePrimeagen How should we go about this? different PRs?

**Comment by ThePrimeagen** [comment]
@cristianoliveira we have had a few changes

this may be fixed by now

**Comment by cristianoliveira** [comment]
Hey there! I'm glad this is solved :D
